### ISSUE TITLE
Undefined Network - "back-tier"

### ISSUE THREAD

**Issue by keyoss** [danifr/internet-pi#7]
`fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Configuration error - Service \"pihole-exporter\" uses an undefined network \"back-tier\""}`

above the error message

Raspi4+ Debian

**Comment by keyoss** [comment]
@danifr :) hope this ping reaches out to you :D

**Comment by danifr** [comment]
Hi @keyoss,

hehe good thing you pinged me :) 

can you share the content of your `config.yml` ?
I think you are missing a variable.

**Comment by keyoss** [comment]
@danifr 

Thought so :D

I have again completely reinstalled the Pi4 - with buster32.
Update / Upgrade
sudo apt-get install -y python3-pip
(was installed already)
pip3 install ansible - went fine
git clone https://github.com/danifr/internet-pi.git
cd internet-pi
git checkout rpi_monitoring
ansible-galaxy collection install -r requirements.yml
cp example files to ini and config
adjusted the config (see attachement)
ansible-playbook main.yml

received an error about the permissions (as usual since the pi user is not set actually) - sudo reboot

ansible-playbook main.yml - again and then : 

fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Configuration error - Service \"pihole-exporter\" uses an undefined network \"back-tier\""}

- config attached :)

regards
k0s
[config.txt](https://github.com/danifr/internet-pi/files/9176023/config.txt)

**Comment by danifr** [comment]
Ah, you need to set  `domain_name_enable` to **_true_** (line 6 of your config.txt file) and then run ansible again.

When it completes you will be able to access your local services via:

- pi-hole: http://pihole.home.local 
- Grafana: http://grafana.home.local 
- prometheus: http://prometheus.home.local

Also, I have been pushing new fixes to the `main` branch, you maybe want to use that branch instead of `rpi_monitoring` :) 

Let me know if that worked for you!

**Comment by keyoss** [comment]
Thanks @danifr 

so i changed the value to true, did rerun and ran into another error.
One thing i did NOT was chnging backc to the branch. Noob question: how to revert back to use the "branch" instead of the rpi_monitoring branch? :/
guess its checkout main?
please find attached errors from rerun the playbook

regards
k0s
[errors_rerun.txt](https://github.com/danifr/internet-pi/files/9176120/errors_rerun.txt)

**Comment by danifr** [comment]
Hmm I think that error is because your `config_dir: '/home/pi/internet-pi/'` needs to be in a different location than the one you have the ansible code.

Let's start from scratch to make sure we are in running it from a clean state:

```
cd ~
rm -rf internet-pi
git clone https://github.com/danifr/internet-pi.git internet-pi
cd internet-pi
```

create `inventory.ini` file with this content:
`127.0.0.1 ansible_connection=local ansible_user=pi`

create `config.yml` with this content:

```
---
# Location where configuration files will be stored.
config_dir: '/home/pi/internet-pi-config/'

# Domain names configuration (related services need to be enabled).
domain_name_enable: true
domain_name: 'home.local'
domain_pihole: 'pihole'          # to access pihole via: http://pihole.home.local
domain_grafana: 'grafana'        # to access grafana via: http://grafana.home.local
domain_prometheus: 'prometheus'  # to access prometheus via: http://prometheus.home.local

# Pi-hole configuration.
pihole_enable: true
pihole_hostname: pihole
pihole_timezone: Europe/Berlin
pihole_password: "admin"

# Raspberry monitoring configuration
raspberry_monitoring_enable: true
telegraf_retention_policy: '90d'
telegraf_password: 'admin'

# Internet monitoring configuration.
monitoring_enable: true
monitoring_grafana_admin_password: "admin"
monitoring_speedtest_interval: 60m
monitoring_ping_interval: 5s
monitoring_ping_hosts:  # [URL];[HUMAN_READABLE_NAME]
  - http://www.google.com/;google.com
  - https://github.com/;github.com
  - https://www.apple.com/;apple.com
  - http://doc-chaos.net/;doc-chaos.net

# Shelly Plug configuration. (Also requires `monitoring_enable`)
shelly_plug_enable: false
shelly_plug_hostname: my-shelly-plug-host-or-ip
shelly_plug_http_username: username
shelly_plug_http_password: "password"

# AirGradient configuration. (Also requires `monitoring_enable`)
airgradient_enable: false
airgradient_sensors:
  # ID Should be limited to no more than 38 characters, in the set a-z.
  - id: livingroom
    ip: "192.168.0.123"
    port: 9925

# Starlink configuration. (Also requires `monitoring_enable`)
starlink_enable: false
```
Then run the ansible code:
`ansible-playbook main.yml `

Let me know :)
